// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_resultset_2eproto__INCLUDED
#define PROTOBUF_resultset_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "table.pb.h"
#include "schema.pb.h"
#include "transaction.pb.h"

namespace drizzled {
namespace message {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_resultset_2eproto();
void protobuf_AssignDesc_resultset_2eproto();
void protobuf_ShutdownFile_resultset_2eproto();

class SelectRecord;
class SelectHeader;
class SelectData;
class Resultset;

// ===================================================================

class SelectRecord : public ::google::protobuf::Message {
 public:
  SelectRecord();
  virtual ~SelectRecord();
  
  SelectRecord(const SelectRecord& from);
  
  inline SelectRecord& operator=(const SelectRecord& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SelectRecord& default_instance();
  void Swap(SelectRecord* other);
  
  // implements Message ----------------------------------------------
  
  SelectRecord* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SelectRecord& from);
  void MergeFrom(const SelectRecord& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated bytes record_value = 1;
  inline int record_value_size() const;
  inline void clear_record_value();
  static const int kRecordValueFieldNumber = 1;
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& record_value() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_record_value();
  inline const ::std::string& record_value(int index) const;
  inline ::std::string* mutable_record_value(int index);
  inline void set_record_value(int index, const ::std::string& value);
  inline void set_record_value(int index, const char* value);
  inline void set_record_value(int index, const void* value, size_t size);
  inline ::std::string* add_record_value();
  inline void add_record_value(const ::std::string& value);
  inline void add_record_value(const char* value);
  inline void add_record_value(const void* value, size_t size);
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> record_value_;
  friend void  protobuf_AddDesc_resultset_2eproto();
  friend void protobuf_AssignDesc_resultset_2eproto();
  friend void protobuf_ShutdownFile_resultset_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SelectRecord* default_instance_;
};
// -------------------------------------------------------------------

class SelectHeader : public ::google::protobuf::Message {
 public:
  SelectHeader();
  virtual ~SelectHeader();
  
  SelectHeader(const SelectHeader& from);
  
  inline SelectHeader& operator=(const SelectHeader& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SelectHeader& default_instance();
  void Swap(SelectHeader* other);
  
  // implements Message ----------------------------------------------
  
  SelectHeader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SelectHeader& from);
  void MergeFrom(const SelectHeader& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .drizzled.message.TableMetadata table_metadata = 1;
  inline int table_metadata_size() const;
  inline void clear_table_metadata();
  static const int kTableMetadataFieldNumber = 1;
  inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::TableMetadata >& table_metadata() const;
  inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::TableMetadata >* mutable_table_metadata();
  inline const ::drizzled::message::TableMetadata& table_metadata(int index) const;
  inline ::drizzled::message::TableMetadata* mutable_table_metadata(int index);
  inline ::drizzled::message::TableMetadata* add_table_metadata();
  
  // repeated .drizzled.message.FieldMetadata field_metadata = 2;
  inline int field_metadata_size() const;
  inline void clear_field_metadata();
  static const int kFieldMetadataFieldNumber = 2;
  inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::FieldMetadata >& field_metadata() const;
  inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::FieldMetadata >* mutable_field_metadata();
  inline const ::drizzled::message::FieldMetadata& field_metadata(int index) const;
  inline ::drizzled::message::FieldMetadata* mutable_field_metadata(int index);
  inline ::drizzled::message::FieldMetadata* add_field_metadata();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::drizzled::message::TableMetadata > table_metadata_;
  ::google::protobuf::RepeatedPtrField< ::drizzled::message::FieldMetadata > field_metadata_;
  friend void  protobuf_AddDesc_resultset_2eproto();
  friend void protobuf_AssignDesc_resultset_2eproto();
  friend void protobuf_ShutdownFile_resultset_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SelectHeader* default_instance_;
};
// -------------------------------------------------------------------

class SelectData : public ::google::protobuf::Message {
 public:
  SelectData();
  virtual ~SelectData();
  
  SelectData(const SelectData& from);
  
  inline SelectData& operator=(const SelectData& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SelectData& default_instance();
  void Swap(SelectData* other);
  
  // implements Message ----------------------------------------------
  
  SelectData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SelectData& from);
  void MergeFrom(const SelectData& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 segment_id = 1;
  inline bool has_segment_id() const;
  inline void clear_segment_id();
  static const int kSegmentIdFieldNumber = 1;
  inline ::google::protobuf::uint32 segment_id() const;
  inline void set_segment_id(::google::protobuf::uint32 value);
  
  // required bool end_segment = 2;
  inline bool has_end_segment() const;
  inline void clear_end_segment();
  static const int kEndSegmentFieldNumber = 2;
  inline bool end_segment() const;
  inline void set_end_segment(bool value);
  
  // repeated .drizzled.message.SelectRecord record = 3;
  inline int record_size() const;
  inline void clear_record();
  static const int kRecordFieldNumber = 3;
  inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::SelectRecord >& record() const;
  inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::SelectRecord >* mutable_record();
  inline const ::drizzled::message::SelectRecord& record(int index) const;
  inline ::drizzled::message::SelectRecord* mutable_record(int index);
  inline ::drizzled::message::SelectRecord* add_record();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 segment_id_;
  bool end_segment_;
  ::google::protobuf::RepeatedPtrField< ::drizzled::message::SelectRecord > record_;
  friend void  protobuf_AddDesc_resultset_2eproto();
  friend void protobuf_AssignDesc_resultset_2eproto();
  friend void protobuf_ShutdownFile_resultset_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SelectData* default_instance_;
};
// -------------------------------------------------------------------

class Resultset : public ::google::protobuf::Message {
 public:
  Resultset();
  virtual ~Resultset();
  
  Resultset(const Resultset& from);
  
  inline Resultset& operator=(const Resultset& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Resultset& default_instance();
  void Swap(Resultset* other);
  
  // implements Message ----------------------------------------------
  
  Resultset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Resultset& from);
  void MergeFrom(const Resultset& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string key = 1;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 1;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  
  // required string schema = 2;
  inline bool has_schema() const;
  inline void clear_schema();
  static const int kSchemaFieldNumber = 2;
  inline const ::std::string& schema() const;
  inline void set_schema(const ::std::string& value);
  inline void set_schema(const char* value);
  inline void set_schema(const char* value, size_t size);
  inline ::std::string* mutable_schema();
  
  // optional string sql = 3;
  inline bool has_sql() const;
  inline void clear_sql();
  static const int kSqlFieldNumber = 3;
  inline const ::std::string& sql() const;
  inline void set_sql(const ::std::string& value);
  inline void set_sql(const char* value);
  inline void set_sql(const char* value, size_t size);
  inline ::std::string* mutable_sql();
  
  // optional .drizzled.message.SelectHeader select_header = 4;
  inline bool has_select_header() const;
  inline void clear_select_header();
  static const int kSelectHeaderFieldNumber = 4;
  inline const ::drizzled::message::SelectHeader& select_header() const;
  inline ::drizzled::message::SelectHeader* mutable_select_header();
  
  // optional .drizzled.message.SelectData select_data = 5;
  inline bool has_select_data() const;
  inline void clear_select_data();
  static const int kSelectDataFieldNumber = 5;
  inline const ::drizzled::message::SelectData& select_data() const;
  inline ::drizzled::message::SelectData* mutable_select_data();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* key_;
  static const ::std::string _default_key_;
  ::std::string* schema_;
  static const ::std::string _default_schema_;
  ::std::string* sql_;
  static const ::std::string _default_sql_;
  ::drizzled::message::SelectHeader* select_header_;
  ::drizzled::message::SelectData* select_data_;
  friend void  protobuf_AddDesc_resultset_2eproto();
  friend void protobuf_AssignDesc_resultset_2eproto();
  friend void protobuf_ShutdownFile_resultset_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Resultset* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// SelectRecord

// repeated bytes record_value = 1;
inline int SelectRecord::record_value_size() const {
  return record_value_.size();
}
inline void SelectRecord::clear_record_value() {
  record_value_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
SelectRecord::record_value() const {
  return record_value_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
SelectRecord::mutable_record_value() {
  return &record_value_;
}
inline const ::std::string& SelectRecord::record_value(int index) const {
  return record_value_.Get(index);
}
inline ::std::string* SelectRecord::mutable_record_value(int index) {
  return record_value_.Mutable(index);
}
inline void SelectRecord::set_record_value(int index, const ::std::string& value) {
  record_value_.Mutable(index)->assign(value);
}
inline void SelectRecord::set_record_value(int index, const char* value) {
  record_value_.Mutable(index)->assign(value);
}
inline void SelectRecord::set_record_value(int index, const void* value, size_t size) {
  record_value_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SelectRecord::add_record_value() {
  return record_value_.Add();
}
inline void SelectRecord::add_record_value(const ::std::string& value) {
  record_value_.Add()->assign(value);
}
inline void SelectRecord::add_record_value(const char* value) {
  record_value_.Add()->assign(value);
}
inline void SelectRecord::add_record_value(const void* value, size_t size) {
  record_value_.Add()->assign(reinterpret_cast<const char*>(value), size);
}

// -------------------------------------------------------------------

// SelectHeader

// repeated .drizzled.message.TableMetadata table_metadata = 1;
inline int SelectHeader::table_metadata_size() const {
  return table_metadata_.size();
}
inline void SelectHeader::clear_table_metadata() {
  table_metadata_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::TableMetadata >&
SelectHeader::table_metadata() const {
  return table_metadata_;
}
inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::TableMetadata >*
SelectHeader::mutable_table_metadata() {
  return &table_metadata_;
}
inline const ::drizzled::message::TableMetadata& SelectHeader::table_metadata(int index) const {
  return table_metadata_.Get(index);
}
inline ::drizzled::message::TableMetadata* SelectHeader::mutable_table_metadata(int index) {
  return table_metadata_.Mutable(index);
}
inline ::drizzled::message::TableMetadata* SelectHeader::add_table_metadata() {
  return table_metadata_.Add();
}

// repeated .drizzled.message.FieldMetadata field_metadata = 2;
inline int SelectHeader::field_metadata_size() const {
  return field_metadata_.size();
}
inline void SelectHeader::clear_field_metadata() {
  field_metadata_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::FieldMetadata >&
SelectHeader::field_metadata() const {
  return field_metadata_;
}
inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::FieldMetadata >*
SelectHeader::mutable_field_metadata() {
  return &field_metadata_;
}
inline const ::drizzled::message::FieldMetadata& SelectHeader::field_metadata(int index) const {
  return field_metadata_.Get(index);
}
inline ::drizzled::message::FieldMetadata* SelectHeader::mutable_field_metadata(int index) {
  return field_metadata_.Mutable(index);
}
inline ::drizzled::message::FieldMetadata* SelectHeader::add_field_metadata() {
  return field_metadata_.Add();
}

// -------------------------------------------------------------------

// SelectData

// required uint32 segment_id = 1;
inline bool SelectData::has_segment_id() const {
  return _has_bit(0);
}
inline void SelectData::clear_segment_id() {
  segment_id_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 SelectData::segment_id() const {
  return segment_id_;
}
inline void SelectData::set_segment_id(::google::protobuf::uint32 value) {
  _set_bit(0);
  segment_id_ = value;
}

// required bool end_segment = 2;
inline bool SelectData::has_end_segment() const {
  return _has_bit(1);
}
inline void SelectData::clear_end_segment() {
  end_segment_ = false;
  _clear_bit(1);
}
inline bool SelectData::end_segment() const {
  return end_segment_;
}
inline void SelectData::set_end_segment(bool value) {
  _set_bit(1);
  end_segment_ = value;
}

// repeated .drizzled.message.SelectRecord record = 3;
inline int SelectData::record_size() const {
  return record_.size();
}
inline void SelectData::clear_record() {
  record_.Clear();
}
inline const ::google::protobuf::RepeatedPtrField< ::drizzled::message::SelectRecord >&
SelectData::record() const {
  return record_;
}
inline ::google::protobuf::RepeatedPtrField< ::drizzled::message::SelectRecord >*
SelectData::mutable_record() {
  return &record_;
}
inline const ::drizzled::message::SelectRecord& SelectData::record(int index) const {
  return record_.Get(index);
}
inline ::drizzled::message::SelectRecord* SelectData::mutable_record(int index) {
  return record_.Mutable(index);
}
inline ::drizzled::message::SelectRecord* SelectData::add_record() {
  return record_.Add();
}

// -------------------------------------------------------------------

// Resultset

// required string key = 1;
inline bool Resultset::has_key() const {
  return _has_bit(0);
}
inline void Resultset::clear_key() {
  if (key_ != &_default_key_) {
    key_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& Resultset::key() const {
  return *key_;
}
inline void Resultset::set_key(const ::std::string& value) {
  _set_bit(0);
  if (key_ == &_default_key_) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void Resultset::set_key(const char* value) {
  _set_bit(0);
  if (key_ == &_default_key_) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void Resultset::set_key(const char* value, size_t size) {
  _set_bit(0);
  if (key_ == &_default_key_) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Resultset::mutable_key() {
  _set_bit(0);
  if (key_ == &_default_key_) {
    key_ = new ::std::string;
  }
  return key_;
}

// required string schema = 2;
inline bool Resultset::has_schema() const {
  return _has_bit(1);
}
inline void Resultset::clear_schema() {
  if (schema_ != &_default_schema_) {
    schema_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Resultset::schema() const {
  return *schema_;
}
inline void Resultset::set_schema(const ::std::string& value) {
  _set_bit(1);
  if (schema_ == &_default_schema_) {
    schema_ = new ::std::string;
  }
  schema_->assign(value);
}
inline void Resultset::set_schema(const char* value) {
  _set_bit(1);
  if (schema_ == &_default_schema_) {
    schema_ = new ::std::string;
  }
  schema_->assign(value);
}
inline void Resultset::set_schema(const char* value, size_t size) {
  _set_bit(1);
  if (schema_ == &_default_schema_) {
    schema_ = new ::std::string;
  }
  schema_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Resultset::mutable_schema() {
  _set_bit(1);
  if (schema_ == &_default_schema_) {
    schema_ = new ::std::string;
  }
  return schema_;
}

// optional string sql = 3;
inline bool Resultset::has_sql() const {
  return _has_bit(2);
}
inline void Resultset::clear_sql() {
  if (sql_ != &_default_sql_) {
    sql_->clear();
  }
  _clear_bit(2);
}
inline const ::std::string& Resultset::sql() const {
  return *sql_;
}
inline void Resultset::set_sql(const ::std::string& value) {
  _set_bit(2);
  if (sql_ == &_default_sql_) {
    sql_ = new ::std::string;
  }
  sql_->assign(value);
}
inline void Resultset::set_sql(const char* value) {
  _set_bit(2);
  if (sql_ == &_default_sql_) {
    sql_ = new ::std::string;
  }
  sql_->assign(value);
}
inline void Resultset::set_sql(const char* value, size_t size) {
  _set_bit(2);
  if (sql_ == &_default_sql_) {
    sql_ = new ::std::string;
  }
  sql_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Resultset::mutable_sql() {
  _set_bit(2);
  if (sql_ == &_default_sql_) {
    sql_ = new ::std::string;
  }
  return sql_;
}

// optional .drizzled.message.SelectHeader select_header = 4;
inline bool Resultset::has_select_header() const {
  return _has_bit(3);
}
inline void Resultset::clear_select_header() {
  if (select_header_ != NULL) select_header_->::drizzled::message::SelectHeader::Clear();
  _clear_bit(3);
}
inline const ::drizzled::message::SelectHeader& Resultset::select_header() const {
  return select_header_ != NULL ? *select_header_ : *default_instance_->select_header_;
}
inline ::drizzled::message::SelectHeader* Resultset::mutable_select_header() {
  _set_bit(3);
  if (select_header_ == NULL) select_header_ = new ::drizzled::message::SelectHeader;
  return select_header_;
}

// optional .drizzled.message.SelectData select_data = 5;
inline bool Resultset::has_select_data() const {
  return _has_bit(4);
}
inline void Resultset::clear_select_data() {
  if (select_data_ != NULL) select_data_->::drizzled::message::SelectData::Clear();
  _clear_bit(4);
}
inline const ::drizzled::message::SelectData& Resultset::select_data() const {
  return select_data_ != NULL ? *select_data_ : *default_instance_->select_data_;
}
inline ::drizzled::message::SelectData* Resultset::mutable_select_data() {
  _set_bit(4);
  if (select_data_ == NULL) select_data_ = new ::drizzled::message::SelectData;
  return select_data_;
}


}  // namespace message
}  // namespace drizzled

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

#endif  // PROTOBUF_resultset_2eproto__INCLUDED
