// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "resultset.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>

namespace drizzled {
namespace message {

namespace {

const ::google::protobuf::Descriptor* SelectRecord_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectRecord_reflection_ = NULL;
const ::google::protobuf::Descriptor* SelectHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectHeader_reflection_ = NULL;
const ::google::protobuf::Descriptor* SelectData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SelectData_reflection_ = NULL;
const ::google::protobuf::Descriptor* Resultset_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Resultset_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_resultset_2eproto() {
  protobuf_AddDesc_resultset_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "resultset.proto");
  GOOGLE_CHECK(file != NULL);
  SelectRecord_descriptor_ = file->message_type(0);
  static const int SelectRecord_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectRecord, record_value_),
  };
  SelectRecord_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SelectRecord_descriptor_,
      SelectRecord::default_instance_,
      SelectRecord_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectRecord, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectRecord, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SelectRecord));
  SelectHeader_descriptor_ = file->message_type(1);
  static const int SelectHeader_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectHeader, table_metadata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectHeader, field_metadata_),
  };
  SelectHeader_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SelectHeader_descriptor_,
      SelectHeader::default_instance_,
      SelectHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectHeader, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectHeader, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SelectHeader));
  SelectData_descriptor_ = file->message_type(2);
  static const int SelectData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectData, segment_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectData, end_segment_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectData, record_),
  };
  SelectData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SelectData_descriptor_,
      SelectData::default_instance_,
      SelectData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SelectData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SelectData));
  Resultset_descriptor_ = file->message_type(3);
  static const int Resultset_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, schema_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, sql_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, select_header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, select_data_),
  };
  Resultset_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Resultset_descriptor_,
      Resultset::default_instance_,
      Resultset_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Resultset, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Resultset));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_resultset_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SelectRecord_descriptor_, &SelectRecord::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SelectHeader_descriptor_, &SelectHeader::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SelectData_descriptor_, &SelectData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Resultset_descriptor_, &Resultset::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_resultset_2eproto() {
  delete SelectRecord::default_instance_;
  delete SelectRecord_reflection_;
  delete SelectHeader::default_instance_;
  delete SelectHeader_reflection_;
  delete SelectData::default_instance_;
  delete SelectData_reflection_;
  delete Resultset::default_instance_;
  delete Resultset_reflection_;
}

void protobuf_AddDesc_resultset_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::drizzled::message::protobuf_AddDesc_table_2eproto();
  ::drizzled::message::protobuf_AddDesc_schema_2eproto();
  ::drizzled::message::protobuf_AddDesc_transaction_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017resultset.proto\022\020drizzled.message\032\013tab"
    "le.proto\032\014schema.proto\032\021transaction.prot"
    "o\"$\n\014SelectRecord\022\024\n\014record_value\030\001 \003(\014\""
    "\200\001\n\014SelectHeader\0227\n\016table_metadata\030\001 \003(\013"
    "2\037.drizzled.message.TableMetadata\0227\n\016fie"
    "ld_metadata\030\002 \003(\0132\037.drizzled.message.Fie"
    "ldMetadata\"e\n\nSelectData\022\022\n\nsegment_id\030\001"
    " \002(\r\022\023\n\013end_segment\030\002 \002(\010\022.\n\006record\030\003 \003("
    "\0132\036.drizzled.message.SelectRecord\"\237\001\n\tRe"
    "sultset\022\013\n\003key\030\001 \002(\t\022\016\n\006schema\030\002 \002(\t\022\013\n\003"
    "sql\030\003 \001(\t\0225\n\rselect_header\030\004 \001(\0132\036.drizz"
    "led.message.SelectHeader\0221\n\013select_data\030"
    "\005 \001(\0132\034.drizzled.message.SelectDataB\002H\001", 519);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "resultset.proto", &protobuf_RegisterTypes);
  SelectRecord::default_instance_ = new SelectRecord();
  SelectHeader::default_instance_ = new SelectHeader();
  SelectData::default_instance_ = new SelectData();
  Resultset::default_instance_ = new Resultset();
  SelectRecord::default_instance_->InitAsDefaultInstance();
  SelectHeader::default_instance_->InitAsDefaultInstance();
  SelectData::default_instance_->InitAsDefaultInstance();
  Resultset::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_resultset_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_resultset_2eproto {
  StaticDescriptorInitializer_resultset_2eproto() {
    protobuf_AddDesc_resultset_2eproto();
  }
} static_descriptor_initializer_resultset_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SelectRecord::kRecordValueFieldNumber;
#endif  // !_MSC_VER

SelectRecord::SelectRecord() {
  SharedCtor();
}

void SelectRecord::InitAsDefaultInstance() {
}

SelectRecord::SelectRecord(const SelectRecord& from) {
  SharedCtor();
  MergeFrom(from);
}

void SelectRecord::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectRecord::~SelectRecord() {
  SharedDtor();
}

void SelectRecord::SharedDtor() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SelectRecord::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectRecord_descriptor_;
}

const SelectRecord& SelectRecord::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_resultset_2eproto();  return *default_instance_;
}

SelectRecord* SelectRecord::default_instance_ = NULL;

SelectRecord* SelectRecord::New() const {
  return new SelectRecord;
}

void SelectRecord::Clear() {
  record_value_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SelectRecord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes record_value = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_record_value:
        DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
              input, this->add_record_value()));
        if (input->ExpectTag(10)) goto parse_record_value;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SelectRecord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    SelectRecord::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // repeated bytes record_value = 1;
  for (int i = 0; i < this->record_value_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->record_value(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SelectRecord::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated bytes record_value = 1;
  for (int i = 0; i < this->record_value_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->record_value(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SelectRecord::ByteSize() const {
  int total_size = 0;
  
  // repeated bytes record_value = 1;
  total_size += 1 * this->record_value_size();
  for (int i = 0; i < this->record_value_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->record_value(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void SelectRecord::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SelectRecord* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectRecord*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectRecord::MergeFrom(const SelectRecord& from) {
  GOOGLE_CHECK_NE(&from, this);
  record_value_.MergeFrom(from.record_value_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SelectRecord::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectRecord::CopyFrom(const SelectRecord& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectRecord::IsInitialized() const {
  
  return true;
}

void SelectRecord::Swap(SelectRecord* other) {
  if (other != this) {
    record_value_.Swap(&other->record_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SelectRecord::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectRecord_descriptor_;
  metadata.reflection = SelectRecord_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SelectHeader::kTableMetadataFieldNumber;
const int SelectHeader::kFieldMetadataFieldNumber;
#endif  // !_MSC_VER

SelectHeader::SelectHeader() {
  SharedCtor();
}

void SelectHeader::InitAsDefaultInstance() {
}

SelectHeader::SelectHeader(const SelectHeader& from) {
  SharedCtor();
  MergeFrom(from);
}

void SelectHeader::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectHeader::~SelectHeader() {
  SharedDtor();
}

void SelectHeader::SharedDtor() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SelectHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectHeader_descriptor_;
}

const SelectHeader& SelectHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_resultset_2eproto();  return *default_instance_;
}

SelectHeader* SelectHeader::default_instance_ = NULL;

SelectHeader* SelectHeader::New() const {
  return new SelectHeader;
}

void SelectHeader::Clear() {
  table_metadata_.Clear();
  field_metadata_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SelectHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .drizzled.message.TableMetadata table_metadata = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_table_metadata:
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, add_table_metadata()));
        if (input->ExpectTag(10)) goto parse_table_metadata;
        if (input->ExpectTag(18)) goto parse_field_metadata;
        break;
      }
      
      // repeated .drizzled.message.FieldMetadata field_metadata = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_field_metadata:
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, add_field_metadata()));
        if (input->ExpectTag(18)) goto parse_field_metadata;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SelectHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    SelectHeader::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // repeated .drizzled.message.TableMetadata table_metadata = 1;
  for (int i = 0; i < this->table_metadata_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageNoVirtual(
      1, this->table_metadata(i), output);
  }
  
  // repeated .drizzled.message.FieldMetadata field_metadata = 2;
  for (int i = 0; i < this->field_metadata_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageNoVirtual(
      2, this->field_metadata(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SelectHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .drizzled.message.TableMetadata table_metadata = 1;
  for (int i = 0; i < this->table_metadata_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->table_metadata(i), target);
  }
  
  // repeated .drizzled.message.FieldMetadata field_metadata = 2;
  for (int i = 0; i < this->field_metadata_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->field_metadata(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SelectHeader::ByteSize() const {
  int total_size = 0;
  
  // repeated .drizzled.message.TableMetadata table_metadata = 1;
  total_size += 1 * this->table_metadata_size();
  for (int i = 0; i < this->table_metadata_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->table_metadata(i));
  }
  
  // repeated .drizzled.message.FieldMetadata field_metadata = 2;
  total_size += 1 * this->field_metadata_size();
  for (int i = 0; i < this->field_metadata_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->field_metadata(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void SelectHeader::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SelectHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectHeader::MergeFrom(const SelectHeader& from) {
  GOOGLE_CHECK_NE(&from, this);
  table_metadata_.MergeFrom(from.table_metadata_);
  field_metadata_.MergeFrom(from.field_metadata_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SelectHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectHeader::CopyFrom(const SelectHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectHeader::IsInitialized() const {
  
  for (int i = 0; i < table_metadata_size(); i++) {
    if (!this->table_metadata(i).IsInitialized()) return false;
  }
  for (int i = 0; i < field_metadata_size(); i++) {
    if (!this->field_metadata(i).IsInitialized()) return false;
  }
  return true;
}

void SelectHeader::Swap(SelectHeader* other) {
  if (other != this) {
    table_metadata_.Swap(&other->table_metadata_);
    field_metadata_.Swap(&other->field_metadata_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SelectHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectHeader_descriptor_;
  metadata.reflection = SelectHeader_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SelectData::kSegmentIdFieldNumber;
const int SelectData::kEndSegmentFieldNumber;
const int SelectData::kRecordFieldNumber;
#endif  // !_MSC_VER

SelectData::SelectData() {
  SharedCtor();
}

void SelectData::InitAsDefaultInstance() {
}

SelectData::SelectData(const SelectData& from) {
  SharedCtor();
  MergeFrom(from);
}

void SelectData::SharedCtor() {
  _cached_size_ = 0;
  segment_id_ = 0u;
  end_segment_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SelectData::~SelectData() {
  SharedDtor();
}

void SelectData::SharedDtor() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* SelectData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SelectData_descriptor_;
}

const SelectData& SelectData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_resultset_2eproto();  return *default_instance_;
}

SelectData* SelectData::default_instance_ = NULL;

SelectData* SelectData::New() const {
  return new SelectData;
}

void SelectData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    segment_id_ = 0u;
    end_segment_ = false;
  }
  record_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SelectData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 segment_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          goto handle_uninterpreted;
        }
        DO_(::google::protobuf::internal::WireFormatLite::ReadUInt32(
              input, &segment_id_));
        _set_bit(0);
        if (input->ExpectTag(16)) goto parse_end_segment;
        break;
      }
      
      // required bool end_segment = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          goto handle_uninterpreted;
        }
       parse_end_segment:
        DO_(::google::protobuf::internal::WireFormatLite::ReadBool(
              input, &end_segment_));
        _set_bit(1);
        if (input->ExpectTag(26)) goto parse_record;
        break;
      }
      
      // repeated .drizzled.message.SelectRecord record = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_record:
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, add_record()));
        if (input->ExpectTag(26)) goto parse_record;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SelectData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    SelectData::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // required uint32 segment_id = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->segment_id(), output);
  }
  
  // required bool end_segment = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->end_segment(), output);
  }
  
  // repeated .drizzled.message.SelectRecord record = 3;
  for (int i = 0; i < this->record_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageNoVirtual(
      3, this->record(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SelectData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 segment_id = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->segment_id(), target);
  }
  
  // required bool end_segment = 2;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->end_segment(), target);
  }
  
  // repeated .drizzled.message.SelectRecord record = 3;
  for (int i = 0; i < this->record_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->record(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SelectData::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 segment_id = 1;
    if (has_segment_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->segment_id());
    }
    
    // required bool end_segment = 2;
    if (has_end_segment()) {
      total_size += 1 + 1;
    }
    
  }
  // repeated .drizzled.message.SelectRecord record = 3;
  total_size += 1 * this->record_size();
  for (int i = 0; i < this->record_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->record(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void SelectData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SelectData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SelectData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SelectData::MergeFrom(const SelectData& from) {
  GOOGLE_CHECK_NE(&from, this);
  record_.MergeFrom(from.record_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_segment_id(from.segment_id());
    }
    if (from._has_bit(1)) {
      set_end_segment(from.end_segment());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SelectData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SelectData::CopyFrom(const SelectData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SelectData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void SelectData::Swap(SelectData* other) {
  if (other != this) {
    std::swap(segment_id_, other->segment_id_);
    std::swap(end_segment_, other->end_segment_);
    record_.Swap(&other->record_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SelectData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SelectData_descriptor_;
  metadata.reflection = SelectData_reflection_;
  return metadata;
}


// ===================================================================

const ::std::string Resultset::_default_key_;
const ::std::string Resultset::_default_schema_;
const ::std::string Resultset::_default_sql_;
#ifndef _MSC_VER
const int Resultset::kKeyFieldNumber;
const int Resultset::kSchemaFieldNumber;
const int Resultset::kSqlFieldNumber;
const int Resultset::kSelectHeaderFieldNumber;
const int Resultset::kSelectDataFieldNumber;
#endif  // !_MSC_VER

Resultset::Resultset() {
  SharedCtor();
}

void Resultset::InitAsDefaultInstance() {
  select_header_ = const_cast< ::drizzled::message::SelectHeader*>(&::drizzled::message::SelectHeader::default_instance());
  select_data_ = const_cast< ::drizzled::message::SelectData*>(&::drizzled::message::SelectData::default_instance());
}

Resultset::Resultset(const Resultset& from) {
  SharedCtor();
  MergeFrom(from);
}

void Resultset::SharedCtor() {
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&_default_key_);
  schema_ = const_cast< ::std::string*>(&_default_schema_);
  sql_ = const_cast< ::std::string*>(&_default_sql_);
  select_header_ = NULL;
  select_data_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Resultset::~Resultset() {
  SharedDtor();
}

void Resultset::SharedDtor() {
  if (key_ != &_default_key_) {
    delete key_;
  }
  if (schema_ != &_default_schema_) {
    delete schema_;
  }
  if (sql_ != &_default_sql_) {
    delete sql_;
  }
  if (this != default_instance_) {
    delete select_header_;
    delete select_data_;
  }
}

const ::google::protobuf::Descriptor* Resultset::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Resultset_descriptor_;
}

const Resultset& Resultset::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_resultset_2eproto();  return *default_instance_;
}

Resultset* Resultset::default_instance_ = NULL;

Resultset* Resultset::New() const {
  return new Resultset;
}

void Resultset::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (key_ != &_default_key_) {
        key_->clear();
      }
    }
    if (_has_bit(1)) {
      if (schema_ != &_default_schema_) {
        schema_->clear();
      }
    }
    if (_has_bit(2)) {
      if (sql_ != &_default_sql_) {
        sql_->clear();
      }
    }
    if (_has_bit(3)) {
      if (select_header_ != NULL) select_header_->::drizzled::message::SelectHeader::Clear();
    }
    if (_has_bit(4)) {
      if (select_data_ != NULL) select_data_->::drizzled::message::SelectData::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Resultset::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_key()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->key().data(), this->key().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectTag(18)) goto parse_schema;
        break;
      }
      
      // required string schema = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_schema:
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_schema()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->schema().data(), this->schema().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectTag(26)) goto parse_sql;
        break;
      }
      
      // optional string sql = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_sql:
        DO_(::google::protobuf::internal::WireFormatLite::ReadString(
              input, this->mutable_sql()));
        ::google::protobuf::internal::WireFormat::VerifyUTF8String(
          this->sql().data(), this->sql().length(),
          ::google::protobuf::internal::WireFormat::PARSE);
        if (input->ExpectTag(34)) goto parse_select_header;
        break;
      }
      
      // optional .drizzled.message.SelectHeader select_header = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_select_header:
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
             input, mutable_select_header()));
        if (input->ExpectTag(42)) goto parse_select_data;
        break;
      }
      
      // optional .drizzled.message.SelectData select_data = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) !=
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          goto handle_uninterpreted;
        }
       parse_select_data:
        DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
             input, mutable_select_data()));
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Resultset::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  ::google::protobuf::uint8* raw_buffer = output->GetDirectBufferForNBytesAndAdvance(_cached_size_);
  if (raw_buffer != NULL) {
    Resultset::SerializeWithCachedSizesToArray(raw_buffer);
    return;
  }
  
  // required string key = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->key(), output);
  }
  
  // required string schema = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->schema().data(), this->schema().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->schema(), output);
  }
  
  // optional string sql = 3;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sql().data(), this->sql().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->sql(), output);
  }
  
  // optional .drizzled.message.SelectHeader select_header = 4;
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageNoVirtual(
      4, this->select_header(), output);
  }
  
  // optional .drizzled.message.SelectData select_data = 5;
  if (_has_bit(4)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageNoVirtual(
      5, this->select_data(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Resultset::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string key = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }
  
  // required string schema = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->schema().data(), this->schema().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->schema(), target);
  }
  
  // optional string sql = 3;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sql().data(), this->sql().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sql(), target);
  }
  
  // optional .drizzled.message.SelectHeader select_header = 4;
  if (_has_bit(3)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->select_header(), target);
  }
  
  // optional .drizzled.message.SelectData select_data = 5;
  if (_has_bit(4)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->select_data(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Resultset::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }
    
    // required string schema = 2;
    if (has_schema()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->schema());
    }
    
    // optional string sql = 3;
    if (has_sql()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sql());
    }
    
    // optional .drizzled.message.SelectHeader select_header = 4;
    if (has_select_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->select_header());
    }
    
    // optional .drizzled.message.SelectData select_data = 5;
    if (has_select_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->select_data());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  _cached_size_ = total_size;
  return total_size;
}

void Resultset::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Resultset* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Resultset*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Resultset::MergeFrom(const Resultset& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_key(from.key());
    }
    if (from._has_bit(1)) {
      set_schema(from.schema());
    }
    if (from._has_bit(2)) {
      set_sql(from.sql());
    }
    if (from._has_bit(3)) {
      mutable_select_header()->::drizzled::message::SelectHeader::MergeFrom(from.select_header());
    }
    if (from._has_bit(4)) {
      mutable_select_data()->::drizzled::message::SelectData::MergeFrom(from.select_data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Resultset::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Resultset::CopyFrom(const Resultset& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Resultset::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_select_header()) {
    if (!this->select_header().IsInitialized()) return false;
  }
  if (has_select_data()) {
    if (!this->select_data().IsInitialized()) return false;
  }
  return true;
}

void Resultset::Swap(Resultset* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(schema_, other->schema_);
    std::swap(sql_, other->sql_);
    std::swap(select_header_, other->select_header_);
    std::swap(select_data_, other->select_data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Resultset::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Resultset_descriptor_;
  metadata.reflection = Resultset_reflection_;
  return metadata;
}


}  // namespace message
}  // namespace drizzled
