/*
  This file was generated by the conf_to_src utility. Do not edit it directly,
  edit the XML definitions in sql/share/charsets/ instead.

  To re-generate, run the following in the strings/ directory:
    ./conf_to_src ../sql/share/charsets/ > FILE
*/

/* Copyright (C) 2000-2007 MySQL AB

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; version 2 of the License.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA */

#include "m_string.h"
#include "m_ctype.h"


CHARSET_INFO compiled_charsets[] = {
{
  0,0,0,
  MY_CS_COMPILED,
  NULL,                       /* cset name     */
  NULL,                       /* coll name     */
  NULL,                       /* comment       */
  NULL,                       /* tailoging     */
  NULL,                       /* ctype         */
  NULL,                       /* lower         */
  NULL,                       /* upper         */
  NULL,                       /* sort order    */
  NULL,                       /* contractions  */
  NULL,                       /* sort_order_big*/
  NULL,                       /* to_uni        */
  NULL,                       /* from_uni      */
  my_unicase_default,         /* caseinfo      */
  NULL,                       /* state map     */
  NULL,                       /* ident map     */
  1,                          /* strxfrm_multiply*/
  1,                          /* caseup_multiply*/
  1,                          /* casedn_multiply*/
  1,                          /* mbminlen      */
  1,                          /* mbmaxlen      */
  0,                          /* min_sort_char */
  255,                        /* max_sort_char */
  ' ',                        /* pad_char      */
  0,                          /* escape_with_backslash_is_dangerous */
  1,                          /* levels_for_compare */
  1,                          /* levels_for_order   */
  &my_charset_8bit_handler,
  &my_collation_8bit_simple_ci_handler,
}
};
